# Generated by Django 5.2.1 on 2025-06-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_phonephoto_media_alter_phonephoto_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonephoto',
            name='media',
            field=models.CharField(default='non', max_length=100),
        ),
        migrations.AlterField(
            model_name='phonephoto',
            name='url',
            field=models.URLField(default='a.com'),
        ),
    ]
