# Generated by Django 5.2.1 on 2025-06-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_phonephoto_media_alter_phonephoto_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonephoto',
            name='url',
            field=models.URLField(default='localhost'),
        ),
    ]
